apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyter-notebook
  name: jupyter-notebook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - image: jupyter/base-notebook
        name: base-notebook
        command:
        - start-notebook.sh
        - --NotebookApp.token=''
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
      # - image: dizex98/tsunami:2
      #   name: tsunami
      #   env: 
      #   - name: TARGET
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: status.podIP      
      #   # args:
      #   # - --ip-v4-target=$(TARGET)
      #   # - --scan-results-local-output-format=JSON
      #   # - --scan-results-local-output-filename=logs/tsunami-output.json
      #   resources:
      #     limits:
      #       memory: "64Mi"
      #       cpu: "250m" 
      #   volumeMounts:
      #   - mountPath: /usr/tsunami/logs
      #     name: logs-volume
      # volumes:
      # - name: logs-volume
      #   emptyDir:
      #     sizeLimit: 500Mi
      
