apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyter-notebook
  name: jupyter-notebook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - image: jupyter/base-notebook
        name: base-notebook
        command:
        - start-notebook.sh
        - --NotebookApp.token=''
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
status: {}
