apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jupyter-notebook
  name: jupyter-notebook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jupyter-notebook
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - image: jupyter/base-notebook
        name: base-notebook
        command:
        - start-notebook.sh
        - --NotebookApp.token=''
        resources: {}
status: {}
