apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tsunami
  name: tsunami
spec:
  containers:
  - image: dizex98/tsunami:2
    name: tsunami
    env:
    - name: IP_TARGET
      value: $(var)
    args:
    - --ip-v4-target=$(IP_TARGET)
    - --scan-results-local-output-format=JSON
    - --scan-results-local-output-filename=logs/tsunami-output.json
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "200m" 
    volumeMounts:
    - mountPath: /usr/tsunami/logs
      name: logs-volume
  volumes:
  - name: logs-volume
    emptyDir:
      sizeLimit: 500Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
