apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tsunami
  name: tsunami
spec:
  containers:
  - image: dizex98/tsunami:2
    name: tsunami
    env:
    - name: IP_TARGET
      valueFrom:
        configMapKeyRef:
          name: ip-target
          key: ip
    args:
    - --ip-v4-target=$(IP_TARGET)
    - --scan-results-local-output-format=JSON
    - --scan-results-local-output-filename=logs/tsunami-output.json
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m" 
    volumeMounts:
    - mountPath: /usr/tsunami/logs
      name: logs-volume
  volumes:
  - name: logs-volume
    hostPath:
      path: /opt/logs
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
